### ISSUE TITLE
PhoneID sending as parameter in sendMessage instead of client config

### ISSUE THREAD

**Issue by tecoad** [MarcosNicolau/whatsapp-business-sdk#28]
Title is self explanatory but..
Have you wondered about making the phoneID as parameter of send message instead of obtained from client?
Think this would enable to have multiple phones under the same service, also making sure that the user gets responded from the same number it has interacted.
Is there any design decision behind making setting up this from client?

**Comment by MarcosNicolau** [comment]
Hi @tecoad, 

Sorry for the late response, this week has been really busy. 😩

So I've been thinking about your suggestion, and tbh I never really though of such case. I guess the design decision was due to the fact that several requests need the `phoneId`. So, to not be passing it around all the time, which would be rather uncomfortable, it made sense to pass it once while instantiating it. Though I do realize now that this come with the limitation of having multiple numbers.

However, couldn't you easily solve it by instatiantion a client per phone. And then, based on the `phoneId` you get on the message, which you can get from the message metadata, you would call the respective client.

**Comment by tecoad** [comment]
@MarcosNicolau 

> So, to not be passing it around all the time, which would be rather uncomfortable, it made sense to pass it once while instantiating it.

Thats exact what i though you had in mind.

> However, couldn't you easily solve it by instatiantion a client per phone. And then, based on the phoneId you get on the message, which you can get from the message metadata, you would call the respective client.

Exactly what i did! Created a function around it passing the phoneId.

If you allow me, another thing i noticed is missing in the package is the ability to fetch a media.

downloadMedia doesn't work if you are working on serverless environment (my case), since fs is not available.

So i have to fetch the media and buffer it to manipulate its data.
So i extended the client with this new method.
```
class ExtendedBABAClient extends WABAClient {
  async fetchMedia(mediaUrl: string) {
    const response = await this.restClient.fetch(mediaUrl, {
      responseType: "arraybuffer",
    });
    return {
      data: response.data,
      filetype: response.headers["content-type"],
    };
  }
```
Wonder someone might need that in the future aswell.
But if you think this make sense would love to submit a PR.

Btw, were you able to check the keys to fix the building?

**Comment by MarcosNicolau** [comment]
Oh yes, please send a pr for that!

I tried to renew the keys but for some reason, my account got suspended and I didn't have time to investigate why.

**Comment by MarcosNicolau** [comment]
Hi @tecoad, 

I've been trying to get my keys but meta is taking their time for it...

I'll probably just create a new account for it and if I can't I will just push the your changes manually (without running the tests 😅). 

Btw, I'd love to see the pr for the feature you mentioned.

**Comment by MarcosNicolau** [comment]
@tecoad I ended up deactivating the client tests for now to push the new changes. Idk how much time will meta take to validate my account... :disappointed: 

Anyway, I am closing this issue. Please feel free to open a new one if you encounter any issues, and thank you very much for your recent contributions! :smiley:
